### ISSUE TITLE
Tracking Consecutive Login Attempts

### ISSUE THREAD

**Issue by charb29** [vigiloauth/vigilo#112]
### Description
**As a** system, **I want** to track consecutive failed login attempts for each account **so that** I can identify when an account should be locked.

### Acceptance Criteria
- [x] The system increments a failure counter for each failed login attempt.
- [x] The system resets the failure counter after a successful login.
- [x] Failed login attempts are tracked separately for each account.
- [x] Update docs
