### ISSUE TITLE
Implement Terminate Session

### ISSUE THREAD

**Issue by vigiloauth** [vigiloauth/vigilo#12]
### Description
Develop the functionality to allow users to terminate active sessions.

### Acceptance Criteria
1. The system allows the user to terminate any active session
2. Once terminated, the session is logged out and cannot be reused.

### Tasks
- [ ] Implement the `terminateSession(sessionId)` method.
- [ ] Make sure that terminated sessions are logged out and cannot be reused.
- [ ] Implement error handling for terminating sessions.
