### ISSUE TITLE
Define Attributes

### ISSUE THREAD

**Issue by vigiloauth** [vigiloauth/vigilo#19]
### Description
Develop the functionality to allow system administrators to define attributes for users and resources.

### Acceptance Criteria:
1. The system allows the administrator to define new attributes.
2. Attributes can be associated with users and resources.
3. The attributes are stored in the database.

### Tasks:
- [ ] Implement the `createAttribute(attributeData)` method.
- [ ] Store the attributes in the database.
- [ ] Implement error handling for attribute creation.
