### ISSUE TITLE
Remove Permission

### ISSUE THREAD

**Issue by vigiloauth** [vigiloauth/vigilo#28]
### Description
Develop the functionality to allow system administrators to remove permissions.

### Acceptance Criteria
1. The system allows the administrator to remove a permission.
2. Roles and users previously assigned the permission lose the associated capabilities.

### Tasks
- [ ] Implement the `deletePermission(permissionId)` method.
- [ ] Update roles and users to remove the associated capabilities.
- [ ] Remove the permission from the database.
- [ ] Implement error handling for permission removal.
