### ISSUE TITLE
Implement Refresh Token

### ISSUE THREAD

**Issue by vigiloauth** [vigiloauth/vigilo#5]
### Description
Develop the functionality to allow users to refresh their JWT token when it expires.

### Acceptance Criteria
1. The system allows the user to provide a refresh token when their JTW token expires.
2. When the refresh token is valid, the user receives a new JWT token.
3. When the refresh token is invalid or expired, the user receives an error message and is prompted to authenticate again.

### Tasks
- [ ] Implement the `refreshToken(refreshToken)` method.
- [ ] Validate the refresh token.
- [ ] Generate and return a new JWT token upon successful validation.
- [ ] Implement error handling for invalid or expired refresh token.
