### ISSUE TITLE
Add Support for Multiple OAuth2 Token Types

### ISSUE THREAD

**Issue by charb29** [vigiloauth/vigilo#51]
### Tasks:
- [ ] Add support for MAC tokens in addition to Bearer tokens. 
- [ ] Update documentation to specify token types supported.
- [ ] Add tests to verify the correct behavior of both Bearer and MAC tokens.

### References:
RFC 6750 - Bearer Token Usage
RFC 6749 - OAuth 2.0 Authorization Framework
