### ISSUE TITLE
Implement Account Recovery

### ISSUE THREAD

**Issue by vigiloauth** [vigiloauth/vigilo#6]
### Description
Develop the functionality to allow users to reset their password if they forget it.

### Acceptance Criteria
1. The system allows the user to request a password reset link via email.
2. The user receives a password reset link.
3. When the user follows the link and enters a new password, their password is successfully updated.
4. When the user follows an invalid or expired password reset link, they receive an error message and are prompted to request a new link.

### Tasks
- [ ] Implement the `recoverAccount(email)` method.
- [ ] Generate and send a password link to the user's email.
- [ ] Implement the `resetPassword(token, newPassword)` method.
