### ISSUE TITLE
Implement Social Media Login

### ISSUE THREAD

**Issue by vigiloauth** [vigiloauth/vigilo#8]
### Description
Develop the functionality to allow users to log in using their social media accounts (Google and Facebook).

### Acceptance Criteria
1. The system allows the user to log in using their social media accounts.
2. When the user logs in with a social media account, their profile is created or linked to an existing account.

### Tasks
- [ ] Implement the `socialLogin(provider, token)` method.
- [ ] Integrate with Google
- [ ] Integrate with Facebook
- [ ] Implement error handling for failed social media logins.
