### ISSUE TITLE
OAuth 2.0 Client Credentials Flow

### ISSUE THREAD

**Issue by charb29** [vigiloauth/vigilo#88]
## User Story
As a server-to-server application developer, I want to implement the Client Credentials flow, So that my backend services can obtain access tokens for machine-to-machine authentication.

## Acceptance Criteria:
1. The library MUST support the Client Credentials grant type for service-to-service authentication.
2. Implement secure client authentication methods:
   - Client secret
   - Private key JWT
   - Mutual TLS
3. Provide flexible scoping for service access rights.
4. Support for token caching to minimize unnecessary token requests.

### Tasks:
- [ ] Implement Client Credentials grant type
- [ ] Add support for multiple client authentication methods
- [ ] Create token caching mechanism
- [ ] Develop comprehensive scoping support
- [ ] Add unit and integration tests

### References:
- RFC 6749 - OAuth 2.0 Authorization Framework
