### ISSUE TITLE
Implement Update Account Details

### ISSUE THREAD

**Issue by vigiloauth** [vigiloauth/vigilo#9]
### Description
Develop the functionality to allow users to update their account detail such as username, email, and password.

### Acceptance Criteria
1. The system allows the user to update their username, email, and password.
2. The system requires the user to verify their email if it is changed.

### Tasks
- [ ] Implement the `updateUserDetails(userId, userDetails)` method.
- [ ] Implement the `verifyEmail(token)` method to confirm the new email address.
- [ ] Implement error handling for invalid or expired verification links.
